### ISSUE TITLE
extra-media.css is not any more in the preview file

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#12]
Although extra-media.css is the default setting in preview.conf, extra-media.css is not any more in the preview file.

**Comment by xiota** [comment]
Thanks for letting me know.  Fixed in a653a5737a39198a62fa77a3fc799209d8af8f56.  There was a typo that was preventing it from loading.  The PPA is being updated.

**Comment by ralf3u** [comment]
>Fixed in a653a57. There was a typo that was preventing it from loading. The PPA is being updated.

still not fixed

**Comment by xiota** [comment]
Another try: 939a3ed5f853ca965db49d60b24e777b158e111e

Updating PPA now.

**Comment by ralf3u** [comment]
>Another try: 939a3ed

fixed
