### ISSUE TITLE
empty Preview for fountain

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#13]
When html and md was not displayed in the Preview-tab (#9), fountain was displayed in the Preview-tab. Since issue number 9 was fixed, it is the other way around: html and md are displayed in the Preview-tab, but not fountain any more.

Fountain can be displayed with a right-click in the Preview-tab, then select in the context menu "Reload". This has to be done each time,
- when changing one word in the editor,
- when switching tabs, and
- after restarting Geany.

**Comment by ralf3u** [comment]
Fixed with the update from today.

But it seems to be that only a snippet of fountain is shown in the Preview-tab, although there is no definition in preview.conf, like
snippet_fountain = true.

**Comment by xiota** [comment]
Does `snippet_screenplain=false` change it?  I need to change the name of that option.  It was from before I wrote my own fountain parser.

**Comment by ralf3u** [comment]
>Does snippet_screenplain=false change it?

no
