### ISSUE TITLE
missing snippet definition for fountain in preview.conf

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#14]
There is only a snippet of fountain in the Preview-tab, although there is no definition for fountain in preview.conf, like `snippet_fountain = true`. To turn `snippet_screenplain=true` to `snippet_screenplain=false` does not change the situation.

**Comment by xiota** [comment]
Fixed in 6908afa2dd893298d17f639415f28c33f534f2af.  Will update PPA.
