### ISSUE TITLE
one-liners for comments in preview.conf

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#16]
At the moment it seems to be that comments have only a certain number of signs per line to avoid long lines. This behavior has five disadvantages:
1) pressure for the author to use short sentences, although sometimes long sentences are necessary for a good explication,
2) harder for the author to edit multi-line comments, because there are some hash-signs between the sentence,
3) harder for the users to read, because it is not so fluid,
4) harder for the users to understand, because it is not so good explained, and
5) harder for the users to copy and paste it in translation tools, because there are some hash-signs between the lines.

If "Line Wrapping" would not exist in Geany, I would understand the use of multi-line comments. But maybe I missed something.

The request for using one-liners should not be used for lists, like for example:
```
#  - native*      - Use the built-in fountain processor
#  - screenplain  - Use screenplain (slower)
#  - disable      - Turn off Fountain screenplay previews
```

The idea to avoid multi-line comments was mentioned for the first time in https://github.com/xiota/geany-preview/issues/9#issuecomment-965687241.

**Comment by xiota** [comment]
Setting scheme changed in 9829a422e4cc4ad6b65b2589a868fd365e611992.  PPA will be updated.
