### ISSUE TITLE
"Loading." for two seconds after every restart of Geany

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#17]
actual behavior
After every restart of Geany there is for about two seconds the text `Loading.` in the content of the Preview-tab, even if only one tab is open in the editor, and even there is only one letter in the document, is it txt, md or html.

expectation
It would be good if the content of an open tab would appear faster in the Preview-tab.

possible solution
If Geany is open and then if I open a document like txt, html or md, then the document is shown right away. So the problem seems to be not the rendering. Maybe something does not work properly when Geany is restarted or there is too much to load, like the load of all parsers. So, what about this idea: Geany Preview should do this after every restart of Geany:
- Load only the parser for the format that is in the editor in the open tab (example: if in the editor in the open tab there is an html-document, then Geany Preview should load only the html-parser).
- After the load of that specific parser and after the rendering of the Preview-tab, then Geany Preview should load all other parsers in the background, so that in the meantime `Loading.` does not appear in the content of the Preview-tab.

**Comment by xiota** [comment]
The webview initializes on a few signals.

* When the plugin is loaded.
* When Geany sends a document/editor signal.
* When Geany sends a startup signal.
* On a timeout after the plugin is loaded or Geany is started.

The problem is on startup, the document isn't ready or the document signals aren't sent.  So it falls back to the timeout.

I'll add an option to change the timeout in a future version.

**Comment by xiota** [comment]
Default timeout changed to 350ms in 09069a8d7f55856a852181f38770b6b71a5d63ef.  Can be changed in `preview.conf`.  PPA will be updated.

**Comment by ralf3u** [comment]
>Default timeout changed to 350ms in 09069a8. Can be changed in preview.conf. PPA will be updated.

Oh!! That's cool!
Thank you so much for this feature.
