### ISSUE TITLE
content of the Preview-tab might shake when snippet is set to false for fountain, md and html

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#23]
Conditions:
- snippet_html=false
- without a background color in the html-code
- very long document

Test 1
- open Geany
- open the very long html-document
- click in the editor and then press Ctrl+home
- in the Preview-tab: place the scrollbars on top of the document
- close Geany
- restart Geany
- type text extremely fast at the top of the document within a div-tag

Result: There is no shaking.

Test 2
- open Geany
- open the very long html-document
- click in the editor and then press Ctrl+end
- in the Preview-tab: place the scrollbars on top of the document
- close Geany
- restart Geany
- type text extremely fast at the end of the document within a div-tag

Result: There is no shaking.

Test 3
Do the same like Test 2, but before to type in the editor:
- in the Preview-tab: scroll with the scrollbars to the end of the document

Result: The content of the Preview-tab is shaking. I think why it is shaking: Because for a part of a second, I can see the top of the webpage. So, it seems to be that it shows first the top of the webpage and then the actual part of the webpage with the change.

Possible solution
Show the content in the Preview after rendering and after the content is fixed.

**Comment by xiota** [comment]
> Show the content in the Preview after rendering and after the content is fixed.

I don't have that level of control of the webview.

Does the document have any tags that look like `<link rel="stylesheet" type="text/css" href="style.css">` ?  If so, that is the cause of the problem.

**Comment by ralf3u** [comment]
>Does the document have any tags that look like `<link rel="stylesheet" type="text/css" href="style.css">` ? If so, that is the cause of the problem. Documents that refer to external CSS files "shake". (I don't know how to fix it besides avoiding using those tags.)

In the html-document there are no internal or external stylesheets. As it is mentioned in the title of that issue, the issue occurs also for md and fountain.

**Comment by xiota** [comment]
It may be related to not having enough time to process the large file.  Does changing the following values in `preview.conf` help?
```
update_interval_fast=150
size_factor_fast=0.002
```

**Comment by ralf3u** [comment]
>It may be related to not having enough time to process the large file. Does changing the following values in preview.conf help?
```
update_interval_fast=150
size_factor_fast=0.002
```

I made a test with fountain. The issue is still there.

**Comment by ralf3u** [comment]
>It may be related to not having enough time to process the large file. Does changing the following values in preview.conf help?

The issue does not appear on your computer?

**Comment by xiota** [comment]
> The issue does not appear on your computer?

It does, but increasing those values helped.  Try higher values... (just to see if it improves).
```
update_interval_fast=300
size_factor_fast=0.004
```

**Comment by ralf3u** [comment]
>It does, but increasing those values helped. Try higher values... (just to see if it improves).

I don't see a big difference.

**Comment by xiota** [comment]
> I don't see a big difference.

If increasing processing time doesn't help, it may be the webview itself (may be out of my control).

**Comment by ralf3u** [comment]
Today, I can't reproduce Test 3 of the report when snippet of html, md and fountain are false, nor with html, nor with md, and nor with fountain. There's no text shaking at all.
