### ISSUE TITLE
preview should not execute html-code of txt-documents

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#24]
Steps to reproduce
Add the following code in a txt-document somewhere on the first page:
 ```
<body style="background:gray">
```
Result: The background of Preview is gray.

Expectation
Preview should not execute html-code of txt-documents. In the browser Firefox and in the browser Web html-code of txt-documents is not executed.

**Comment by xiota** [comment]
What is the name of the file?  It is probably being detected as a different filetype.  I'll check if there's some other issue.

**Comment by ralf3u** [comment]
>What is the name of the file?

The name of the txt-document is geany_test.txt.

**Comment by xiota** [comment]
Plain text documents are not supposed to show up in the preview (because they're just a duplicate of what's in the editor).  So there's something wrong with filetype detection.

**Comment by ralf3u** [comment]
>... there's something wrong with filetype detection.

Should I do something?
All my txt-documents are shown in the Preview.

**Comment by xiota** [comment]
I just checked the code.  Apparently I changed it at some point to show in the preview.  I am looking into fixing it and will update the PPA soon

**Comment by ralf3u** [comment]
>... will update the PPA soon

Well, as I mentioned before, it is not necessary because I wanted to use the auto-sidebar anyway.

**Comment by xiota** [comment]
> Well, as I mentioned before, it is not necessary because I wanted to use the auto-sidebar anyway.

Okay.  Will update when it's done.  (Pretty much already done, but has performance issues.)

**Comment by xiota** [comment]
Fixed in 6a6f7c8a167de859135fa95a16e8141b43582331.

**Comment by ralf3u** [comment]
>Fixed in 6a6f7c8.

I can confirm.
