### ISSUE TITLE
a blinking vertical line in the Preview only for visible text as option for html

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#26]
If the issue #19 can be solved, then this issue could be interesting: A blinking vertical line in the Preview to show the position of the cursor of the editor, for all the code or only for visible text. Example: If in the editor the cursor is just before the body-tag, then the blinking vertical line should not appear in the preview, if in preview.conf the setting is `blinking_vertical_line_for_visible_text_html=true`. With the setting `blinking_vertical_line_for_visible_text_html=true` the blinking vertical line should also not appear for text with the css `visibility: hidden` or `display: none`.

The default settings in preview.conf could be something like this:
`blinking_vertical_line=false`
`blinking_vertical_line_for_visible_text_html=true`

**Comment by xiota** [comment]
Can you explain briefly how this is different from #19?

**Comment by ralf3u** [comment]
>Can you explain briefly how this is different from #19?

In issue number 19 the blinking vertical line is either not in the preview or always in the preview.
In issue number 26 there is a further differentiation. The blinking vertical line is in html-documents, when set to true, only visible if in the editor the symbol before the cursor is visible in the preview. So for example, if in the editor the cursor is just before the body-tag, then the blinking vertical line should not appear in the preview.

**Comment by xiota** [comment]
That seems more or less like a duplicate to me.  Either way, I don't know how to transfer the needed info between editor and webview.

**Comment by ralf3u** [comment]
>That seems more or less like a duplicate to me.

I think this explication is better:
- In issue number 19 the blinking vertical line is either not in the preview or always in the preview.
- In issue number 26 the blinking vertical line is either not in the preview or, except html-documents, always in the preview. For html-documents: The blinking vertical line will only appear if the symbol just before the place of the blinking vertical line is a visible symbol in the preview.

Number of transfers from the editor to the preview:
- In issue number 19 there is only one transfer from the editor to the preview, namely the position of the cursor.
- In issue number 26 there are two tranfers from the editor to the preview, namely the position of the cursor and the symbol before the cursor, to check in the preview if the symbol before the place of the blinking vertical line is the same symbol like in the editor. So, for example if there is this code `<br><br><br><br>` and in the editor the cursor is between the code, then the blinking vertical line would not appear in the preview.

**Comment by ralf3u** [comment]
I recognized today that for this issue not two signals need to be transferred from the editor to the preview, but three signals:
- position of the cursor
- symbol before the cursor
- symbol after the cursor

Then Preview could do something like that: IF ((symbol before cursor in the editor = symbol before cursor in the sidebar) OR (symbol after cursor in the editor = symbol after cursor in the sidebar)) THEN DO show blinking vertical line.
