### ISSUE TITLE
txt-document: a colon plus space in the very first line after the first expression shows different background color

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#30]
Steps to reproduce
- open Geany (as css: extra-media.css)
- put a txt-document in focus
- type in the very first line completely on the left: `tzz: `

Result
The first line has a different background color. And the whole text of the document appears in the preview.

Expectation
There should be no different background color. And there should be an empty preview.

**Comment by xiota** [comment]
This is caused by the email header detection.  The `tzz:` is treated similarly to other headers, like `Subject:`.

**Comment by xiota** [comment]
I'll look at the regex to see if I can reduce false positives when detecting headers, but otherwise, this is intended behavior.  You can control the style that is used for headers with the `geany_preview_headers` rules in `preview.css`.

**Comment by ralf3u** [comment]
I can confirm that issue is fixed.
