### ISSUE TITLE
the tab-title "Preview" disappears if all other tabs of the sidebar are disabled

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#32]
Current situation
If, except the Preview-tab, all other tabs of the sidebar are disabled, then there is no "Preview" as tab-title any more.

Expectation
It would be good, if the Preview-tab-title is always visible as default, even if all other tabs of the sidebar are disabled. As option the tab-title "Preview" could be disabled with something like `title_preview=false`, if all other tabs of the sidebar are disabled.

Possible solution
So, in `preview.conf` there could be this kind of text:
```
# title_preview=true*:	tab-title "Preview" is always visible
# title_preview=false:	tab-title "Preview" disappears, if all other tabs of the sidebar are disabled
title_preview=true
```
Remark
If one use only the tab "Preview", then at the moment there is no visible effect for the tab-title "Preview" when sidebar is in focus (see #5).

**Comment by xiota** [comment]
This looks like a bug.  Shouldn't happen in the first place (not to be fixed with an option).

**Comment by ralf3u** [comment]
> This looks like a bug.

Could you please add the bug-label to this issue? Thank you in advance.

**Comment by xiota** [comment]
I just tried it, and the tabs disappearing is probably done on purpose by Geany.  It's not something that would be easy to change with a plugin, and I doubt Geany devs would want to make any changes to make the tab bar stay put.

**Comment by ralf3u** [comment]
In the report of this issue is this text:

>If one use only the tab "Preview", then at the moment there is no visible effect for the tab-title "Preview" when sidebar is in focus (see https://github.com/xiota/geany-preview/issues/5).

Thanks to the plugin Xi/Tweaks now there is a visible effect when tab-title "Preview" is in focus.

If the menu bar and tool bar are disabled and if there is no other tab than Preview in the sidebar:
On one side there is the editor and on the other side there is just the webpage, and nothing else. That's quite cool.

**Comment by ralf3u** [comment]
FYI, I just opened at Geany the issue number 4557 with this title:
"There is no tab bar in the sidebar if there is only one tab in the sidebar".
