### ISSUE TITLE
a name of a shortcut is too long

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#34]
`Toggle focus between editor and preview pane.`
I would change it like this:
`Toggle focus editor/preview`

An alternative if my suggestion is not welcome:
`Toggle focus between editor and preview`

By the way, I would also delete the points from the other two shorcuts, because in the Preferences, in Keybindings, nearly all names have no point at the end.

**Comment by xiota** [comment]
Done.

**Comment by ralf3u** [comment]
The shortcut was changed from
`Toggle focus between editor and preview pane.`
to
`Toggle focus between the editor and preview`

I would delete also the`the`, else I ask myself why there is not also a "the" before "preview".
So, I think this would be better:
`Toggle focus between editor and preview` as I mentioned already in my report as alternative on top of this web-page.

**Comment by ralf3u** [comment]
The name of the shortcut is still too long. The `the` should be deleted, also because it is creating confusion https://github.com/xiota/geany-preview/issues/34#issuecomment-1059766167.
And now it is even more necessary to change the name of the shortcut to have a better separation to the new possible shortcut name https://github.com/xiota/geany-preview/issues/40 (I just opened that issue some minutes ago).
Could you please reopen this issue?

**Comment by xiota** [comment]
I don't think one word is significant, but I've removed "the" from my local source.  The PPA won't be updated until there are more significant changes.

**Comment by ralf3u** [comment]
@xiota
For security reasons I would like to give you my email-address, because nobody knows how the future will be with github.com. My email-address is pierre-yves AT mnet-online.de. I will delete this post on in some seconds.
