### ISSUE TITLE
Gecko for rendering webpages as option

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#35]
Because I like to use Firefox, I would prefer that the webpages would be rendered in Geany Preview not with WebKit2GTK but with Gecko. Maybe there could be the possibility to choose the engine in preview.conf. Example:
```
default     - WebKit2GTK
gecko	    - Gecko (engine of the browser Firefox)
qtwebengine - QtWebEngine (engine of the browser Falkon)
html_render=default
```

**Comment by xiota** [comment]
As far as I can tell, Gecko is not available for GTK.  Even Firefox is no longer available in Ubuntu repositories (it redirects to a snap package).
