### ISSUE TITLE
opening a document from the file-manager does not put the document in focus when Geany was closed

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#36]
condition
open Geany 
open some documents, like txt- and html-documents
close Geany

steps to reproduce
open the file-manager
mark a document, like a txt- or html-document
press enter

result
Geany is now open but the document is not in focus; the document is in focus, which was the last time in focus when closing Geany

expectation
Geany should put the document in focus which was marked in the file-manager

remark
I wanted to open an issue on github.com/xiota/geany, but I can't find the link "issues".
Should I open an issue on github.com/geany/geany/issues/, or is it a problem that only concerns the PPA?

software
Lubuntu 22.04
Geany 1.39

**Comment by ralf3u** [comment]
@xiota 
I just found your report on github.com/geany/geany/issues/ in number 3210, that you made 15 days ago with this title:
"Geany doesn't switch to newly opened document when restoring previously opened files".

**Comment by xiota** [comment]
Yes, it is an upstream issue.  Don't know if they plan to leave it or fix it.

At xiota/geany, apparently the setting to show issues was turned off.  Don't know why.  It is turned on now.  If you have anymore problems with the PPA, please let me know.

As a workaround, you can put the following script somewhere in your path.  

```
#!/usr/bin/env bash

# this script works around behavior where geany does not activate newly
# opened documents on start, but does when arguments are passed to an
# already running instance

GEANY_EXEC="/usr/bin/geany"

if pgrep geany ; then
  if [ $# -eq 0 ] ; then
    # bring already running instance to foreground
    xdotool search --desktop 0 --onlyvisible --class geany windowactivate
  else
    # pass arguments to already running instance
    $GEANY_EXEC "$@" &
  fi
else
  # run geany, then pass arguments to new instance
  $GEANY_EXEC &
  [ $# -ne 0 ] && sleep 1 && $GEANY_EXEC "$@"
fi
```

**Comment by xiota** [comment]
It depends on how the `PATH` variable is setup.  Maybe try `~/bin`.  You may need to log out and back in for the startup scripts to pick up the new directories.  Look in `~/.profile` for lines that look like the following:
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
        PATH="$HOME/.local/bin:$PATH"
fi
```

**Comment by ralf3u** [comment]
> Also, you would need to `chmod +x` the script file for it to run.

That was the thing that was missing: `sudo chmod +x ~/.local/bin/geany`.
Just for information: For me it is better to use a DELAY of 0.6 instead of 0.5.
Now it works perfect. Thank you so much for that script.

**Comment by xiota** [comment]
Glad it's working.  When the underlying issue is resolved, I will update the PPA and let you know the script can be removed.
