### ISSUE TITLE
Add libpodofo-dev to build dependencies

### ISSUE THREAD

**Issue by bgvaughan** [xiota/geany-preview#46]
I just built geany-preview on Debian Sid. Installing the build requirements pulled in libpodofo0.9.8 as a dependency. However, I found that I needed to install libpodofo-dev for configure to complete. After that, it compiled without error.

**Comment by xiota** [comment]
Aside from updating documentation, what specifically do you want updated?

**Comment by bgvaughan** [comment]
It was just a documentation issue.
