### ISSUE TITLE
make fails on Debian Unstable

### ISSUE THREAD

**Issue by bgvaughan** [xiota/geany-preview#47]
I was able to build geany-preview on this system previously, but it's failing currently.

[geany-preview.log](https://github.com/xiota/geany-preview/files/12508081/geany-preview.log)

**Comment by xiota** [comment]
Thank you for letting me know.  I will be looking at it over the next few days / week.  I no longer use Debian/Ubuntu, so after pushing changes, your feedback on what happens on Debian will be helpful.

**Comment by xiota** [comment]
Problem looks like a stray copy/paste.  Should work now.
