### ISSUE TITLE
geany crashes after launch with 

### ISSUE THREAD

**Issue by bgvaughan** [xiota/geany-preview#48]
Preview, the plugin, is set to be loaded automatically. After recompiling and installing the updated geany-preview (as of Sept 4), geany immediately crashes.
[geany_2023-09-04.log](https://github.com/xiota/geany-preview/files/12516955/geany_2023-09-04.log)

**Comment by xiota** [comment]
This might take longer to diagnose.  Do you have an old working build you can use while waiting?

**Comment by xiota** [comment]
Should be fixed now.
