### ISSUE TITLE
when sidebar is in focus: visible effect of the tab

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#5]
It happened to me already many times that I lost the orientation when working with shortcuts in Geany because I didn't know which pane is now in focus: editor or sidebar.

Let's imagine this situation: A document, that is already saved, is longer than the visible area. The current line is on top of the document. With the mouse the user is scrolling down, so that the current line is not any more in the visible area. Now the user is distracted by something. Then the user looks back on the screen. What is in focus? Is it the editor or Preview? There is no hint at all. Now let's imagine the same situation with visible effect of the tab when sidebar is in focus. Now there is a hint: Because the Preview-tab has no visible effect, it means that the editor is in focus.

So, that were my thoughts today:
An other background-color for the tab would be good. Or an other font-color. Or what about a kind of star-symbol after the word Preview? A symbol after the word Preview could be interesting but I don't like when there is an addition, because it is not minimalist. What if the font-color is the same font-color like the font-color of the unsaved tab in the editor? Yes, but in Preview there is nothing like "unsaved". So there should be different colors for a clear separation. So, what about if the font-color would be in green? Hey, that sounds good! A kind of soft green color. The green color reminds me of a traffic light when people are crossing the street. A color reminds me of children, because children like to play with colors. Colors reminds me also of a toy to play. Yes, and coding is playing. All those point of views make so much sense. So I have a good feeling for the green color as font-color when the Preview-tab is in focus. But maybe I will not like the effect.

Is there a possibility to change the font-color of the Preview-tab when it is in focus? If so, where can I change the settings?

Nevertheless I think that the idea of a green font-color is a good idea. The Preview-tab would have then, when it is in focus, some kind of smiling, warm and lovely character. Or what about this idea: When Preview-tab is in focus, then the font-color should be green by default, and at the same time giving the users the possibility in a script to change the font-color?

What about #46af41?
#46af41: I found this color today by pressing in the color spectrum in Gimp.
I tested the color in the tab of the editor for unsaved tab. I like it.

On one side there is the red color for the unsaved tab in the editor, and on the other side there would be the green color when Preview is in focus or when other tabs of the sidebar are in focus. It would be some kind of nice color game that fits together.

**Comment by xiota** [comment]
> I lost the orientation when working with shortcuts in Geany because I didn't know which pane is now in focus: editor or sidebar.
> What is in focus? Is it the editor or Preview? There is no hint at all.

The editor highlights the current line.  If no line is highlighted, the editor does not have focus.

> Is there a possibility to change the font-color of the Preview-tab when it is in focus?
> On one side there is the red color for the unsaved tab in the editor, and on the other side there would be the green color when Preview is in focus or when other tabs of the sidebar are in focus. It would be some kind of nice color game that fits together.

There is currently no setting in the preview plugin itself.  I will think about whether I would want to add something like this.  If I do, it would be off by default.  Since you are now familiar with the conf file, you should have no difficulty turning it on.

> If so, where can I change the settings?

Since you are working with HTML files, maybe there is something you could do with javascript?  YouTube stops video playback when the page loses focus.  So there must be a way to detect and respond to it.

**Comment by ralf3u** [comment]
@xiota

>The editor highlights the current line. If no line is highlighted, the editor does not have focus.

That is not true. Here is the evidence:
Let's imagine this situation: The highlighted line is on top of the document. With the mouse the user is scrolling down, so that the highlighted line is not any more in the visible area. Now the user is distracted by something. Then the user looks back on the screen. What is in focus? Is it the editor or Preview? There is no hint at all.


You write:
>The problem is I'm not able to connect to any signals to find out when the Preview tab gets and loses focus.

So, to detect when tab gets and loses focus does exist only for the editor and not for the sidebar?
<br>
Thank you for an answer in advance.

**Comment by xiota** [comment]
> > The editor highlights the current line. If no line is highlighted, the editor does not have focus.
> 
> That is not true... With the mouse the user is scrolling down, so that the highlighted line is not any more in the visible area... There is no hint at all.

Okay.

> So, to detect when tab gets and loses focus does exist only for the editor and not for the sidebar?

1. The editor is a different component. (scintilla)
2. I can test for focus, but that is not useful if it is not done at the right time.
3. Something could be blocking the signals for the sidebar.

I'll look at the editor some other time to see if it is doing anything special.  But right now, this is most likely not possible.

**Comment by xiota** [comment]
@ralf3u I found a different signal I can use.  It's not specifically for focus, but I can check for focus after receiving it.  There are new options in the config file: `preview_tab_focus_green`, `preview_tab_focus_bold`.  They are disabled by default, so you will have to enable them.

By now you know the routine... reset config, save config, edit config, reload config... etc.

**Comment by ralf3u** [comment]
@xiota

Yes!! It's nearly perfect.

issue 1
I don't like so much the green color. It seemed to be that you took an other green color. In the colorscheme sleepy pastel the green color is a little bit too dark for me. Is there a possibility to choose an other green color like the color I mentioned above (#46af41)?
I know how to change the color of the tab-title for an unsaved document, but I don't know to change the color of the tab-title of the sidebar.

issue 2
But what about the other tabs of the sidebar, like Documents or Symbols? I mean, this is for me not so important. But it would be good if it would work on all tabs of the sidebar for the reason to deliver a consequent behavior.

Thank you for an answer in advance.

**Comment by xiota** [comment]
> But what about the other tabs of the sidebar, like Documents or Symbols?

I'll take a look.  I'm probably going to move this feature to a different plugin.

> I don't like so much the green color.

I'll make it customizable later.

**Comment by ralf3u** [comment]
@xiota

I forgot to mention also the plugin Filemanager (or something like this), that I'm using. It shows all documents of a certain file in a tab in the sidebar. So, also that tab should have the green font-color when it is in focus and if preview_tab_focus_green=true.

remark: I don't see so much the necessity in preview_tab_focus_bold because in the editor the title of the tab that is in focus is also not bold.

**Comment by xiota** [comment]
@ralf3u  I put this feature in a different plugin.  Basically it is for miscellaneous stuff that doesn't really belong in the Preview plugin.  It will be in the PPA shortly.  The package name is `geany-plugin-xi-tweaks`.  You can install with:
```
sudo apt-get update
sudo apt-get install geany-plugin-xi-tweaks
```
The new plugin has similar buttons and menu items to edit the config files as the Preview plugin.  The color of the tabs can be changed.  After you get this working, I will remove the tab highlighting from the Preview plugin.

**Comment by ralf3u** [comment]
@xiota

Wow!! From the effect level it is marvelous!!
It makes fun to tab-browse!! What a feeling!!
<br><br>

issue 1
I don't know if that happened in other versions of Geany Preview and I don't know if it has to do something with this new feature, but now I recognize this:
On a very long document, so that I can see in the editor only a part of the document in the visible area, there is this when I go to the last line of the document after some seconds:
In the sidebar, in the Preview-tab, there is at the very first line some strange text that is marked, like: "shorcut stays down".
<br><br>

issue 2
open Geany
press the shortcut toggle editor/sidebar
press again the shortcut toggle editor/sidebar
result: the green color stays in the sidebar
<br><br>

issue 3
open Geany
condition 1: the editor is on the left side; the sidebar is on the right side
condition 2: the Symbols-tab is in the sidebar the first tab
click on the Preview-tab
close Geany
open Geany
press the shortcut toggle editor/sidebar
in the sidebar: tab-browse with shortcuts to the left, to the first tab of the sidebar, so to the Symbols-tab
in the sidebar: continue to tab-browse with shortcuts to the left
result: a tab of the editor is in focus
expected result: the last tab on the right side of the sidebar should be in focus
<br><br>

remark: behavior that I like:
open Geany
click in the sidebar on a tab that is not the Preview-tab
close Geany
open Geany
press the shortcut toggle editor/sidebar
result: Preview-tab is in focus (that's good!)

**Comment by xiota** [comment]
Implemented in another plugin: https://github.com/xiota/geany-tweaks

**Comment by xiota** [comment]
PPA has been updated with another attempt.

**Comment by ralf3u** [comment]
>PPA has been updated with another attempt.

The issue number 3 of this webpage is fixed.

issue 4
But now the problem is, that there are some small points around the Preview-tab-title when it is in focus. During tab-browsing in the sidebar, there are some small points around the corresponding focused tab-title. Some days ago there were no points at all. I think that the points are standing for focus. I feel a little bit disturbed by the points.

possible solution
The focus should not be on the tab-title but on the content of the tab.

model for a possible solution
In the editor there are no points at all around the tab-title when a tab of the editor is in focus.

control after the solution was realized
a: There should be no points for all tab-title of the sidebar, when a tab of the sidebar is in focus.
b: There should be no points for all tab-title of the sidebar, when switching with shortcut (toggle editor/sidebar) or by clicking on a tab-title of the sidebar.

**Comment by xiota** [comment]
> But now the problem is, that there are some small points around the Preview-tab-title when it is in focus.

I don't know what you are describing.  Please show a screenshot.

>  The focus should not be on the tab-title but on the content of the tab.

I'll add this if it can be done without restructuring any of the existing code.  Otherwise, this has been difficult to implement, and I'd prefer to avoid making changes that will break it.

**Comment by ralf3u** [comment]
>I don't know what you are describing. Please show a screenshot.

![2021-11-01](https://user-images.githubusercontent.com/68117017/139668387-38376210-0046-4882-bbd2-3413a8dc9a24.jpg)

There are now small white points around the tab-title Preview.

**Comment by xiota** [comment]
> There are now small white points around the tab-title Preview.

That does not happen on my computer.  What theme are you using?

Try adding:  `border-style: none;`

**Comment by ralf3u** [comment]
>What theme are you using?

Still the same theme:
My theme Qt-style is kvantum-dark.
GTK 2-Theme: Arc-Dark
GTK 3-Theme: Arc-Dark
my window theme (in openbox): KvGnomeDark
in Geany: colorscheme: Sleepy Pastel

>Try adding: border-style: none;

Where?

**Comment by xiota** [comment]
I don't know what package the Arc themes are from, so cannot install them to test.

> > Try adding: border-style: none;
>
> Where?

To `geany.css`, under the `#geany-xitweaks-sidebar-tab-focus` rule.

**Comment by ralf3u** [comment]
>To geany.css, inside the #geany-xitweaks-sidebar-tab-focus rule.

After restarting Geany it is still there.

**Comment by xiota** [comment]
> Two days ago it was not there, so something was added yesterday.

Turn off the plugin to see if it is still there.

I installed a bunch of dark themes.  It looks like something that is controlled by the theme.  Did you update Ubuntu to 21.10?  The theme may have changed.

Go to `/usr/share/themes`.  Find the theme folder.  There will be a `css` file somewhere inside.  Look to see how the border is implemented.  Then you can try adding a modified version of the rule to `geany.css`.

**Comment by ralf3u** [comment]
>Turn off the plugin to see if it is still there.

I turned off Xi/Tweaks in the list of plugins. Then I restarted Geany. It is still threre.

>Did you update Ubuntu to 21.10?

No.

>Go to /usr/share/themes. Find the theme folder.

In the folder themes there are 50 folders. Which one should I take?
My theme Qt-style is kvantum-dark.
GTK 2-Theme: Arc-Dark
GTK 3-Theme: Arc-Dark
my window theme (in openbox): KvGnomeDark

**Comment by xiota** [comment]
Geany uses GTK3.

I found the arc themes package... I see the outline now.  It is part of the theme when the tab has keyboard focus.  I turned off all plugins and removed `geany.css`, and it is still there.

**Comment by ralf3u** [comment]
Should I do something?

**Comment by xiota** [comment]
> Should I do something?

I put some `css` in another message that may help.  I will update the PPA momentarily.

**Comment by ralf3u** [comment]
What works:
- editor is in focus; shortcut toggle editor/sidebar is pressed: Preview is green
- clicking in the sidebar on a tab-title: tab-title is green

Old issue, still not fixed:
- clicking in the sidebar in the content of a tab: tab-title should be green

Maybe I have a solution: What about this:
- open Geany
- choose a txt-document in the editor
- click in the content of the Preview-tab
- now press the shortcut toggle editor/sidebar

Result: The editor is again in focus. What I want to say with that is: In the moment where I click in the content of the Preview-tab, there must be some signal, else afterwards the shortcut would not work correctly.
So the solution is: There is the signal to make then the tab-title green.

**Comment by xiota** [comment]
> In the moment where I click in the content of the Preview-tab, there must be some signal, else afterwards the shortcut would not work correctly.

The shortcut doesn't need to use any signal to detect what is in focus.  It works on-demand.  When you press the keys, the function is called, then it does the checks.

I guess I *could* have a function constantly running to check what's in focus.  It would affect performance and might still have problems.

**Comment by ralf3u** [comment]
Summary of that issue till now:

What works:
- shortcut toggle editor/sidebar is pressed: Preview is green
- clicking in the sidebar on a tab-title: tab-title is green

What does not work:
- clicking in the sidebar in the content of a tab: the tab-title is not green (old issue, still not fixed)

<br>

This is the code for the green color to add at the end of geany.css:
```
notebook header tabs > * {
	outline-width: 0;
}

#geany-xitweaks-sidebar-tab-focus {
	font-weight: bold;
	color: #46af41;
}
#geany-xitweaks-sidebar-tab-unfocus {
	/* Whatever you want */
}

#geany-xitweaks-sidebar-page-focus {
	border-width: 3px;
	border-style: solid;
	border-color: #46af41;
}

#geany-xitweaks-sidebar-page-unfocus {
	border-width: 3px;
	border-style: solid;
	border-color: transparent;
	background: #2e3436;
}

#geany-preview-sidebar-page {
	border-width: 3px;
	border-style: solid;
	border-color: transparent;
	background: #2e3436;
}
```

**Comment by ralf3u** [comment]
I wanted to reopen this issue because it was not completely fixed. But there is no "Reopen issue"-button like in some other closed issues.

**Comment by ralf3u** [comment]
Maybe the solution of this issue has a connection with https://github.com/xiota/geany-preview/issues/15.

**Comment by ralf3u** [comment]
YESSS!!!!!!!

The only thing what does not work in this issue is:
>clicking in the sidebar in the content of a tab: the tab-title is not green (old issue, still not fixed)

I noticed that here: https://github.com/xiota/geany-preview/issues/5#issuecomment-969031972

But today I'm sure: There must be a solution for this issue!

Because if (in a html-document with the highlighted line in the editor) I press 1x or 2x the shortcut "Toggle editor" what you developed last week (https://github.com/xiota/geanylua-scripts/issues/4), and then, if I click in the content of the Preview, then the tab-title is green!

Could be maybe interesting for understanding what's going on: Before pressing the shortcut: If I click first in the content of the Preview, then the tab-title will later not become green.

A solution for this issue would be so great.

**Comment by ralf3u** [comment]
To my last comment:
Could you figure out why in one case the tab-title becomes green, but not in the other case, or rather could you catch a signal that fires the green color so that this issue could be solved?

**Comment by ralf3u** [comment]
Before programing shortcuts for issue number 37, 38 and 40, I think that this issue is more important. It is so close to be perfect. Maybe my comment in https://github.com/xiota/geany-preview/issues/5#issuecomment-1158852295 could help to solve this issue.

**Comment by xiota** [comment]
I don't currently have the plugin built/installed because I switched distros.  Also, this thread is really long touching on multiple related issues.  Could you briefly summarize what the current issue is?

**Comment by ralf3u** [comment]
> Could you briefly summarize what the current issue is?

The only thing that does not work for that issue:
If I type in the editor, and then if I click in the content of the Preview, then the tab-title will not become green.

I think that there should be a solution because of this behavior:
If I type in the editor, and then if I press the shortcut for the lua-script https://github.com/xiota/geanylua-scripts/issues/4, and then, if I click in the content-area of the Preview, then the tab-title becomes green.

**Comment by xiota** [comment]
> ... the tab-title will not become green...

That is probably a focus issue.  Trying to change focus hasn't worked well.  I'm stuck and don't know how to fix it.

**Comment by ralf3u** [comment]
>I'm stuck and don't know how to fix it.

... although it works perfect with the lua-script?

**Comment by ralf3u** [comment]
>Trying to change focus hasn't worked well. I'm stuck and don't know how to fix it.

I just opened https://github.com/geany/geany/issues/3289 to bring a little bit movement to the topic.

**Comment by ralf3u** [comment]
>Maybe GTK4 is different, but in GTK3 almost a year ago, none of the signals worked. When focus was grabbed, often the wrong widget was selected. (https://github.com/geany/geany/issues/3289#issuecomment-1247469392)

So, would that mean that maybe this issue could be fixed with GTK4, like the other issues mentioned in the report of https://github.com/geany/geany/issues/3289#issue-1369859705?

**Comment by xiota** [comment]
I doubt it's "fixed" in GTK4, but even if it were, Geany still requires GTK3.  (GTK4 removes deprecated features that Geany still uses.)

**Comment by ralf3u** [comment]
>I doubt it's "fixed" in GTK4, but even if it were, Geany still requires GTK3. (GTK4 removes deprecated features that Geany still uses.)

That's such a pity. It was my last hope.

**Comment by ralf3u** [comment]
>I doubt it's "fixed" in GTK4, but even if it were, Geany still requires GTK3. (GTK4 removes deprecated features that Geany still uses.)

The only thing I really miss in Geany Preview is the focus feature (#5, #15, #37, #38). It would make Geany Preview so perfect for non-scrolling webpages.

What about the idea to test GTK4 and if there is still an issue, then to report it upstream, so to the GTK folks, like elextr suggested (https://github.com/geany/geany/issues/3289#issuecomment-1247476031), so that maybe one day the focus feature could be solved?

I mean, I can imagine that it is a lot of work, but it's worth.

**Comment by xiota** [comment]
> What about the idea to test GTK4

Geany and plugins would have to be built with GTK4.  I think there is a build flag for that.  I will look for it.

> The only thing I really miss in Geany Preview is the focus feature... I can imagine that it is a lot of work, but it's worth.

I'm inclined not to mess with it, but I'll think about it.

**Comment by ralf3u** [comment]
>Geany and plugins would have to be built with GTK4. I think there is a build flag for that. I will look for it.

Oh, that would be so great!

>I'm inclined not to mess with it, but I'll think about it.

For me the focus-feature is an important fun-factor. It's such a pleasure to see the tab-title in green. At the same time it is an important symbol for orientation. I do believe that where is fun, there is success. I can imagine that Geany Preview can become a popular software, specially if the focus-feature works. Because then, Geany Preview can't be made even better for non-scrolling webpages. It's just perfect then. And I think that users are looking for perfection.

**Comment by xiota** [comment]
> For me the focus-feature is an important fun-factor. It's such a pleasure to see the tab-title in green.

I agree that it is fun to see the tabs changing.  But it's frustrating that focus was never quite where you wanted it (eg, keyboard navigation).  I'm not a GTK expert, so there might be something I'm missing.

**Comment by ralf3u** [comment]
>But it's frustrating that focus was never quite where you wanted it (eg, keyboard navigation).

At the moment there is no issue with the keyboard. The issue occurs only with the mouse (https://github.com/xiota/geany-preview/issues/5#issuecomment-969031972 and #15).

> I'm not a GTK expert, so there might be something I'm missing.

And what about to start reporting a bug at GTK? And then maybe, someone will give an interesting help.

**Comment by ralf3u** [comment]
I think that the focus issues can be reduced to two issues:

#5: with a click in the content of the Preview-tab: change color of tab-title, and
#15:: a release of a click on the tab-title: the content of the Preview-tab should be in focus.

**Comment by xiota** [comment]
I was mistaken about geany having gtk4 support.  I just tried building geany with gtk4, by swapping out gtk3 references with gtk4, and it fails.

**Comment by ralf3u** [comment]
>I just tried building geany with gtk4, by swapping out gtk3 references with gtk4, and it fails.

So, this issue and issue #15 should keep an eye on the evolution of https://github.com/geany/geany/issues/2713.
Thank you for your try.

**Comment by ralf3u** [comment]
>>I'm not a GTK expert, so there might be something I'm missing.
>
>And what about to start reporting a bug at GTK? And then maybe, someone will give an interesting help.

**Comment by xiota** [comment]
> And what about to start reporting a bug at GTK? And then maybe, someone will give an interesting help.

Unless you can confirm there's actually a bug, I think it's better not to report bugs upstream.  Would be better to find a support forum to ask how to change keyboard focus to the desired widget, and provide code examples of what isn't working.

**Comment by ralf3u** [comment]
>Would be better to find a support forum to ask how to change keyboard focus to the desired widget, and provide code examples of what isn't working.

I couldn't find a GTK forum. I mean, because of reporting one single bug at GTK, that maybe is not a bug, I can't imagine that the reporter will be punished. And maybe it is a bug. I can't report a bug because I have no knowledge in coding software.

**Comment by xiota** [comment]
In this instance, changing focus seems like something that should already be possible, but I don't know how.  Developers react to bug reports/feature requests differently.  Some are unpleasant to interact with, so I think it's better to confirm bugs before reporting.

**Comment by xiota** [comment]
> I would like to report a bug at gitlab.gnome.org.

I don't think it's a good idea to report this as a bug unless you can write and compile code for testing.  Look for a GTK tutorial to get some small test programs up and running.

Otherwise, what would most likely happen is they would close it saying it's downstream's fault for not knowing how to code it.  If you have a small test program that demonstrates the problem, they would be able to tell you how to fix it.

> no way to control color of tab-title of the sidebar...

There is a way to change the color, with the gtk.css file.  The problem is forcing specific widgets to grab keyboard focus or detecting when focus has moved.  Most of the problems you described, occur when you use the keyboard to navigate.

**Comment by ralf3u** [comment]
>Most of the problems you described, occur when you use the keyboard to navigate.

I don't understand this sentence. You wrote this kind of sentence already two times in the past (https://github.com/xiota/geany-preview/issues/5#issuecomment-1257142523:
>But it's frustrating that focus was never quite where you wanted it (eg, **keyboard navigation**).

https://github.com/xiota/geany-preview/issues/5#issuecomment-1262828777:
> Would be better to find a support forum to ask **how to change keyboard focus** to the desired widget [...]

I wrote in https://github.com/xiota/geany-preview/issues/5#issuecomment-1257162848:
>At the moment there is no issue with the keyboard. The issue occurs only with the mouse (https://github.com/xiota/geany-preview/issues/5#issuecomment-969031972 and https://github.com/xiota/geany-preview/issues/15).

And I mentioned also in https://github.com/xiota/geany-preview/issues/5#issuecomment-1258585894:
>I think that the focus issues can be reduced to two issues:
https://github.com/xiota/geany-preview/issues/5: with a click in the content of the Preview-tab: change color of tab-title, and
https://github.com/xiota/geany-preview/issues/15:: a release of a click on the tab-title: the content of the Preview-tab should be in focus.

Maybe I missed something. But why you mentioned at least three times that it is a keyboard navigation problem although it is only a mouse problem?

**Comment by ralf3u** [comment]
>The problem is forcing specific widgets to grab keyboard focus [...]

Why does the focus feature work so perfect with the shortcut "Toggle focus between editor and sidebar"?
And why can the focus-part not be copied and pasted in all other shortcuts (like #37, #38 and #40)?

**Comment by xiota** [comment]
I don't remember what I implemented where.  I'm looking at the Preview plugin, and it looks like I made it toggle between editor and preview.  The xi/tweaks plugin looks like it toggles between editor and sidebar.  I also wrote and submitted a patch for geany to add the toggle focus features, but closed it because of lack of upstream interest (unlikely it would ever be accepted).

I didn't add those features to Preview because they seem to be outside the scope of showing previews.  Maybe I will add them some of them to the TweaksUI plugin.

**Comment by ralf3u** [comment]
Could the focus-part be copied and pasted in other shortcuts (like https://github.com/xiota/geany-preview/issues/37, https://github.com/xiota/geany-preview/issues/38 and https://github.com/xiota/geany-preview/issues/40)?

**Comment by xiota** [comment]
> Could the focus-part be copied and pasted in other shortcuts (like https://github.com/xiota/geany-preview/issues/37, https://github.com/xiota/geany-preview/issues/38 and https://github.com/xiota/geany-preview/issues/40)?

Not exactly copy/paste, but they're doable.  I just think it's outside the scope of the Preview plugin.  So it's a matter of deciding whether I want to mess with it and if so, where to put them.  I guess I could put them into the Xi/Tweaks or TweaksUI plugins, but it's been a while since I've looked at them, so would have to refamiliarize myself with the code.

**Comment by ralf3u** [comment]
>Not exactly copy/paste, but they're doable.

Oh, that would be great! Then all keyboard navigation would work perfect!

> I just think it's outside the scope of the Preview plugin.

I don't think so, because scrolling right away in the Preview with the keyboard (with the arrow-keys) is not an unusual behavior.

**Comment by xiota** [comment]
My understanding is #37 is to toggle visibility of the sidebar.  #38 is to toggle visibility of the editor.  And #40 is to toggle focus between editor and sidebar.  I believe #40 is already implemented in Xi/Tweaks.  Are you still using that plugin?

**Comment by ralf3u** [comment]
>I believe https://github.com/xiota/geany-preview/issues/40 is already implemented in Xi/Tweaks.

I use Xi/Tweaks only for the colored tab-title of the sidebar. See detailed manual of installation and configuration in https://github.com/xiota/geany-preview/issues/5#issuecomment-969031972.

>Are you still using that plugin?

Not at the moment because I reinstalled Lubuntu. But I will use it in the next hours.

**Comment by ralf3u** [comment]
I don't know if it is helpful information when programing the focus-feature for shortcuts, but I just recognized that in Geany, in the Preferences, in Keybindings in the Action `Focus` there is the entry `Switch to Sidebar`. I have no idea how to program software, but if one could know how the shortcut works, then I can imagine that one could copy & paste the code.

**Comment by ralf3u** [comment]
Here a step-by-description for having a green font color of the tab-title of the sidebar when sidebar is in focus:

 The code down below need to be added at the end of `geany.css` that is located in `~/.config/geany/` (if `geany.css` does not exist there, then first do this: copy `/usr/share/geany/geany.css` to `~/.config/geany/geany.css`):
```
notebook header tabs > * {
	outline-width: 0;
}

#geany-xitweaks-sidebar-tab-focus {
	font-weight: normal;
	color: #7dcc95;
}
#geany-xitweaks-sidebar-tab-unfocus {
	/* Whatever you want */
}

#geany-xitweaks-sidebar-page-focus {
	border-width: 3px;
	border-style: solid;
	border-color: #2e3436;
}

#geany-xitweaks-sidebar-page-unfocus {
	border-width: 3px;
	border-style: solid;
	border-color: transparent;
	background: #2e3436;
}

#geany-preview-sidebar-page {
	border-width: 3px;
	border-style: solid;
	border-color: transparent;
	background: #2e3436;
}
```
Then save the document. If there is till no green effect, then those things need to be done:
- activate in the Plugin-Manager the plugin `Xi/Tweaks`
  (if Xi/Tweaks is not in the list, then you need first to install it:  `sudo apt install geany-plugin-xi-tweaks`) 
- in `.config/geany/plugins/xitweaks` change in `xitweaks.conf` `sidebar_focus_enabled=false` to `sidebar_focus_enabled=true`; then save the document `xitweaks.conf`, and then close the document; go to menu-bar Edit, Plugin-Preferences, Xi/Tweaks and click on `Reload Config`, `Apply` and `OK`; restart Geany and verify in `xitweaks.conf`if `sidebar_focus_enabled=true`

The reason for the code `notebook header tabs > * {outline-width: 0;}` is to avoid this behavior: If the shortcut "Toggle focus between the editor and preview" was pressed, then, as long as Geany is not closed, there are white points around the tab-title on a long click on an open tab of the editor or sidebar.

If the content of `geany.css` (that is located in `~/.config/geany/`) will be changed, then save the document, and restart Geany to see the changes.

**Comment by ralf3u** [comment]
>I don't know if it is helpful information when programing the focus-feature for shortcuts, but I just recognized that in Geany, in the Preferences, in Keybindings in the Action Focus there is the entry Switch to Sidebar. I have no idea how to program software, but if one could know how the shortcut works, then I can imagine that one could copy & paste the code.

It was my mistake to publish those lines above, because the solution is not to switch focus to the sidebar. The solution is to switch focus to the content area of the Preview-tab.

**Comment by ralf3u** [comment]
I have a question to your comment https://github.com/geany/geany/issues/3289#issuecomment-1244794854. You write:

>The problem is not just knowing whether a widget has focus, but also setting focus on the widget of interest.

Specially this part of the sentence is for me interesting:
> [..] but also setting focus on the widget of interest.

This is for me strange. Because you write in https://github.com/xiota/geany-preview/issues/5#issuecomment-1272538526:
>Not exactly copy/paste, but they're doable.

So, if it is doable with keyboard navigation, then it could be doable also for click navigation by some kind of copy/paste.

Then, that would mean that there is only one single issue that could to be asked at GTK:
>The problem is [...] knowing whether a widget has focus [...]

Or I would write it like this to solve #5 and #15:
The problem is if sidebar has focus.

Is this correct?

**Comment by xiota** [comment]
> The solution is to switch focus to the content area of the Preview-tab.

This is the problem.  Focus switches to the sidebar, but I have no control over which specific widget has focus.

I recall you had issues with the wrong tab being highlighted when using the keyboard (arrow keys?) to switch tabs.

**Comment by ralf3u** [comment]
>I recall you had issues with the wrong tab being highlighted when using the keyboard (arrow keys?) to switch tabs.

This does not occur with the shortcut "Toggle between editor and sidebar". This does only occur, when clicking on the tab-title of the sidebar.

I don't know how to program software. But let's say the shortcut "Toggle between editor and sidebar" is pressed, then a function A is executed that put the content area of the Preview-tab in focus. It runs perfect. Why this function A can not be used, when clicking on the tab-title of the sidebar? Because at the moment it is like this: When clicking on the tab-title of the sidebar, the tab-title is green. Is it not possible to say: IF tab-title is green THEN run function A?

**Comment by xiota** [comment]
Maybe geany/geany pulls/2919

**Comment by ralf3u** [comment]
On this https://github.com/xiota/geany-preview/issues/5#issuecomment-965578494 there is this text:
>Old issue, still not fixed:
    clicking in the sidebar in the content of a tab: tab-title should be green

Thanks to the plugin Xi/Tweaks this is issue is completely fixed for the Preview-tab, but not for the Files-tab (plugin `File Browser`) of the sidebar.

**Steps to reproduce**
1. click on the tab-title of the Files-tab
2. click on the tab-title of the editor
3. click in the content area of the Files-tab (result: the content area of the Files-tab is in focus)

**Result**
the tab-title Files-tab does not show a sign that it has focus

**Result**
the tab-title Files-tab should be underlined because the tab is in focus

**Comment by ralf3u** [comment]
There is also an other issue in Lubuntu 23.10 in Geany 1.38 when using the plugin "File Manager":

**Steps to reproduce**
1. click on the tab-title of the Files-tab
3. click in the content area of the Files-tab (result: the content area of the Files-tab is in focus)

**Result**
the tab-title Files-tab does not show a sign any more that it has focus

**Result**
the tab-title Files-tab should be underlined because the tab is in focus

**Comment by ralf3u** [comment]
And there is a last issue in Lubuntu 23.10 in Geany 1.38 when using the plugin "File Manager":

**Steps to reproduce**
1. click on the tab-title of the Files-tab
2. click in the content area of the Files-tab (result: the content area of the Files-tab is in focus)
3. tab-browse with the keyboard (ctrl+Pageup/Pagedown) forward and backward

**Result**
the tab-title Files-tab does not show a sign that it has focus

**Result**
the tab-title Files-tab should be underlined because the tab is in focus

**Comment by ralf3u** [comment]
You don't need to do anything, because I will make first a test on an other computer. I will be back in some hours.

**Comment by ralf3u** [comment]
I just made some tests on an other computer. Could it be that my last comments has to do something with https://github.com/xiota/geany-preview/issues/15#issuecomment-2012520206?

**Comment by ralf3u** [comment]
The title of this issue is fixed thanks to the plugin Xi/Tweaks.

For reasons of documentation here are the settings that work:
1) Content of `xitweaks.conf` that is located at `.config/geany/plugins/xitweaks/`:
```
[tweaks]
sidebar_focus_enabled=false
notebook_focus_enabled=true
```
2) At the end of `geany.css` that is located in `.config/geany/`:
```
/* design of the tab-title of active tabs (so, one tab of the editor, one tab of the sidebar and one tab of the message window) */
tab:checked {
	font-weight: bold;
}

/* design of the tab-title of the tab that is in focus */
#geany-xitweaks-notebook-tab-focus,
#geany-xitweaks-notebook-tab-focus label {
	border-bottom: 5px solid black;
}

/* design of the tab-title of the tabs that are not in focus */
#geany-xitweaks-notebook-tab-unfocus,
#geany-xitweaks-notebook-tab-unfocus label {
	border-bottom: 5px solid transparent;
}

```

**Comment by ralf3u** [comment]
The code in my last comment is about to have the same design of the tab-title on different panels (editor / sidebar / message window) for the tab that has focus. It is interesting specially for ePaper-displays.

Here is an example if someone wants a special design only for the tab-titles that are in the sidebar :
1) Content of `xitweaks.conf` that is located at `.config/geany/plugins/xitweaks/`:
```
[tweaks]
sidebar_focus_enabled=true
notebook_focus_enabled=false
```
2) At the end of `geany.css` that is located in `.config/geany/`:
```
/* design of the tab-title of the tab that is in focus */
#geany-xitweaks-notebook-tab-focus,
#geany-xitweaks-notebook-tab-focus label {
	color: lightgreen;
}

/* design of the tab-title of the tabs that are not in focus */
#geany-xitweaks-notebook-tab-unfocus,
#geany-xitweaks-notebook-tab-unfocus label {
	color: black;
}
```

**Comment by ralf3u** [comment]
Could you please delete the two labels "enhancement" and "wontfix" because the issue is fixed?

**Comment by ralf3u** [comment]
**Remark to the plugin Xi/Tweaks**
I would put only those lines in the document `xitweaks.conf`:
```
[tweaks]
sidebar_focus_enabled=false
notebook_focus_enabled=false
```
And then I would put a description in a `readme.txt` that is located in the same folder where the document xitweaks.conf is stored.
