### ISSUE TITLE
Other shortcut name than "Toggle focus between editor and preview"

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#50]
This is the current shortcut name:
```
Toggle focus between editor and preview
```
My opinion is that the shortcut name is too long. My suggestion:
```
Focus editor ↔ focus preview
```
It's shorter and therefore better.

**Comment by xiota** [comment]
I'm not putting special symbols (↔) in the shortcut name.  It doesn't match the existing style of all the other shortcut names and has many potential problems.
