### ISSUE TITLE
Add the shortcut "Reload the active tab of the editor in the preview"

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#56]
The shortcut "Reload the active tab of the editor in the preview" could be interesting when testing links.

**Comment by xiota** [comment]
This is low priority because preview is refreshed when document is switched or changed.

**Comment by ralf3u** [comment]
When I press ctrl+r then the document in the editor is shaking al little bit, but not the preview. It seems to be that the process of reload is slow. I don't have this kind of shake when reloading a webpage in the browser Firefox. Does the shake also happen on the computer that you are using?

**Comment by ralf3u** [comment]
Ah, I just recognized that the shake in the editor happens when the scrollbar of the editor is not on top.

**Comment by xiota** [comment]
The document is reloaded, so things may move when redisplayed.
