### ISSUE TITLE
How to change the CSS in preview.css for marked text?

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#57]
On a eink-display in text-mode, in the editor, before to mark the text, the text is in black, while marked text appears in white with black background, so I can see marked text.
In the preview-tab on a LCD/TFT-display, marked text has a gray background. But on a eink-display in text-mode, there is no background color on marked text, so I have big difficulties to see which text is marked.
What would be the CSS in preview.css to change the color and the background color of marked text?

**Comment by xiota** [comment]
I haven't tested, but maybe this helps.  https://www.w3schools.com/howto/howto_css_text_selection.asp

**Comment by ralf3u** [comment]
I inserted this CSS-code at the end of preview.css:
```
::selection {
  color: white;
  background: black;
}
```
Thank you for your help.
