### ISSUE TITLE
Where is the code of the plugin Xi/Tweaks located on the internet?

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#62]
The code as zip-file of the plugin `Preview` can be found when visiting https://github.com/xiota/geany-preview and by clicking there on the green button `Code`.
But I don't know where to find the code as zip-file of the plugin Xi/Tweaks.

**Comment by xiota** [comment]
That plugin is not in a repo yet.  I'm planning to do make one eventually.  The code can be downloaded from the PPA (have to click around to find link).  Looks like Ubuntu 24.10 was released earlier this month, so have to update.

**Comment by ralf3u** [comment]
> Looks like Ubuntu 24.10 was released earlier this month, so have to update.

I don't know if an update is necessary. I upgraded from Lubuntu 24.04 to Lubuntu 24.10 some days ago. The plugins Preview, Lua Scripts and Xi/Tweaks are working fine.

**Comment by ralf3u** [comment]
>The code can be downloaded from the PPA (have to click around to find link).

I found this:
https://launchpad.net/~xiota/+archive/ubuntu/geany-plugins
On that webpage I found:
geany-plugin-xi-tweaks 	1:0.0.0-r32.g9900a17-1[...]ppa1[...]ubuntu22.04
But I don't know how to download the code.

**Comment by xiota** [comment]
Click link "View package details".  Click the triangle expander next to the package you're interested in.  There should be links under heading "Package files".  Source code has extension `.orig.tar.xz`.  The `.debian.tar.xz` files are used for packaging.  The `.deb` files can be used directly if you don't want to install the PPA.

**Comment by ralf3u** [comment]
>Click link "View package details". Click the triangle expander next to the package you're interested in. There should be links under heading "Package files". Source code has extension .orig.tar.xz. The .debian.tar.xz files are used for packaging. The .deb files can be used directly if you don't want to install the PPA.

It worked for me. Thank you for your help.
