### ISSUE TITLE
gray background in the Preview-tab after every restart of Geany

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#7]
For a part of a second there is a gray background in the Preview-tab after every restart of Geany.
With the help of the software simplescreenrecorder, VLC and colorpicker I could define the exact background color: The background color is `#3f4551`. It is the same background color like the background color of the tab-title.

It would be great if the background color could be customized, so that the gray background will not be visible any more.
In the editor there is no change of the background color after every restart of Geany.

**Comment by ralf3u** [comment]
>Is the version of xitweaks 20211028.134628 or later?

Just for interest: How can I identify my used version of xitweaks?

**Comment by ralf3u** [comment]
@xiota 

>Is the version of xitweaks 20211028.134628 or later?

Just for interest: How can I identify my used version of xitweaks?

Unfortunately code was erased in the comments of xitweaks.conf. The value `geany-preview-sidebar-page` is missing in the comments in order to customize the gray background. Please add it as comment in xitweaks.conf. I think it would be good to add a sentence of explication in the comments, something like:
With geany-preview-sidebar-page the background color of the Preview-tab can be customized.

**Comment by xiota** [comment]
> How can I identify my used version of xitweaks?

`sudo apt show geany-plugin-xi-tweaks`

> The value geany-preview-sidebar-page is missing in the comments in order to customize the gray background.

That is no longer part of the xi/tweaks plugin.  (BTW, it has its own project page now: [xiota/geany-tweaks](https://github.com/xiota/geany-tweaks))  Instructions are in the questions document: [CQA.md](https://github.com/xiota/geany-preview/blob/main/docs/CQA.md).

**Comment by ralf3u** [comment]
As consequence to your response https://github.com/xiota/geany-preview/issues/2#issuecomment-961277596 to my comment https://github.com/xiota/geany-preview/issues/2#issuecomment-961238377, what about to add background.css (with the code down below) to the list in preview.conf to complete the list?
```
	html {
		background: #2e3436;
	}
```

**Comment by xiota** [comment]
Is this for the `extra_css` option?  Isn't that already in `extra-dark.css`.

**Comment by ralf3u** [comment]
>Is this for the extra_css option? Isn't that already in extra-dark.css.

It is indeed part of extra-dark.css. But in extra-dark.css there are also more styles. But I want that only the gray background is fixed (see title of this issue), and nothing more.

By the way: I just recognize that there is another issue: Although in preview.conf there is `extra_css=extra-media.css`, the document extra-media.css does not exist in the file preview.

**Comment by ralf3u** [comment]
>By the way: I just recognize that there is another issue: Although in preview.conf there is extra_css=extra-media.css, the document extra-media.css does not exist in the file preview.

Because this does not belong in this issue, I just opened a new for that (issue number 12: "extra-media.css is not any more in the preview file").

**Comment by ralf3u** [comment]
On https://github.com/xiota/geany-preview/blob/main/docs/CQA.md it is described how the gray background after every restart of Geany can be avoided. There it would be good if it would be also mentioned how to avoid the gray background when the plugin Xi/Tweaks is also used.

And it would be good to add the following code at the end of preview.conf as comment, in case a user has no internet connection any more:

```
To avoid for a part of a second a gray background in the content area of the Preview-tab after every start of Geany:
Copy /usr/share/geany/geany.css to ~/.config/geany/geany.css. Restart Geany after adding rules similar to the following:
If the plugin Xi/Tweaks is not activated in the list of plugins:
#geany-preview-sidebar-page {
	background: white;
}
If the plugin Xi/Tweaks is activated in the list of plugins:
#geany-preview-sidebar-page {
	background: white;
}
#geany-xitweaks-sidebar-page-unfocus {
	background: white;
}
```
