### ISSUE TITLE
markdown-documents are not displayed correctly

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#8]
Create in the editor a document with the name test.md.
Write `**hh**` in the editor.

Result
- in the Preview there is this text: `**hh**`, and it is not bold
- in the editor there is `**hh**`, but what is strange: it is bold

<br>

In the editor Formiko it shown as it should be:
- in the Preview hh is bold, and without stars
- in the editor `**hh**` is not bold

In the editor ReText, hh is also shown correct in the preview: bold and without stars.

**Comment by xiota** [comment]
That is strange.  What is the document type that Geany detects the `md` file as?  It should be in the status bar.

**Comment by ralf3u** [comment]
>What is the document type that Geany detects the md file as? It should be in the status bar.

Filetype: Markdown

**Comment by ralf3u** [comment]
Preview: issue is now fixed, so hh is now bold and without stars
editor: still not fixed

**Comment by xiota** [comment]
> Preview: issue is now fixed, so hh is now bold and without stars

To clarify: HTML and Markdown documents now display in the Preview pane with formatting as expected?

> editor: still not fixed

What is this?  Please describe in more detail.

**Comment by ralf3u** [comment]
>To clarify: HTML and Markdown documents now display in the Preview pane with formatting as expected?

yes


>>editor: still not fixed
>
>What is this? Please describe in more detail.

In the editor `**hh**` is in bold. In Formiko it is not bold in the editor.

**Comment by xiota** [comment]
> In the editor **hh** is in bold. In Formiko it is not bold in the editor.

That is a feature built into Geany.  Not controlled by my plugin.

**Comment by ralf3u** [comment]
>That is a feature built into Geany. Not controlled by my plugin.

I found this: https://github.com/geany/geany/issues/1497#issuecomment-302266150
Do you know how it works to change it, so that it is not bold any more in markdown?

**Comment by xiota** [comment]
I don't know how.  It isn't something I want to mess with.
